---
shell_packages:
  - bash-completion
  - zsh

resource_monitor_packages:
  - sysstat
  - dstat
  - lsof
  - htop
  - iotop
  - powertop

network_monitor_packages:
  - tcpdump
  - nmap
  - netcat-traditional

editor_packages:
  - emacs-nox
  - vim
