---
galaxy_info:
  role_name: iptables
  author: Ivo Amorim
  description: Role to initialize iptables rules
  license: "BSD"
  min_ansible_version: 1.0
  platforms:
    - name: centos
      versions:
        - 7
    - name: debian
      versions:
        - 9
  galaxy_tags:
    - networking
    - system
    - security
    - firewall
    - iptables
    - tcp
dependencies: []
