---
- hosts: all
  gather_facts: yes

  vars_files:
    - vars/logrotate-{{ ansible_os_family }}.yml
    - vars/ssh-hardening.yml
    - vars/ntp.yml

  roles:
    - ivoamorim.selinux
    - ivoamorim.iptables
    - ivoamorim.syslog
    - ivoamorim.package_utilities
    - dev-sec.ssh-hardening
    - geerlingguy.ntp
    - ivoamorim.packages
    - ivoamorim.logrotate
