---
# Install sysstat, dstat, lsof, wide range of top
install_resource_monitor_packages: true

# Install tcpdump, nmap, netcat
install_network_monitor_packages: true

# Install Bash, Zsh
install_shell_packages: false

# Install Emacs, Vim
install_editor_packages: true
