---
- include_vars: "{{ ansible_os_family }}.yml"

- name: Install rsyslog
  package:
    name: "rsyslog"
    state: present

- name: Setup rsyslog configure
  template:
    src: "{{ item.name }}.j2"
    dest: "{{ item.path }}"
    backup: yes
  notify:
    - restart rsyslog
  with_items:
    - { name: "rsyslog", path: "/etc/rsyslog.conf" }
    - { name: 'rsyslog-rules', path: "/etc/rsyslog.d/default.conf" }

- name: Setup logrotate
  include_role:
    name: ivoamorim.logrotate
  #vars:
  #  logrotate_scripts: "{{ logrotate_files }}"
