---
- include_vars: "{{ ansible_os_family }}.yml"

- name: Install Resource Monitor Packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ resource_monitor_packages }}"
  when: install_resource_monitor_packages

- name: Install Network Monitor Packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ network_monitor_packages }}"
  when: install_network_monitor_packages

- name: Install Shell Packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ shell_packages }}"
  when: install_shell_packages

- name: Install Editor Packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ editor_packages }}"
  when: install_editor_packages
